name: snipfy

services:
  gateway:
    container_name: snipfy-gateway
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    networks:
      - snipfy

networks:
  snipfy:
    driver: bridge
